accounts/urls.py
from django.urls import path
from .import views 




urlpatterns =[
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('activate/<uidb64>/<token>/',views.activate,name='activate'),
    path('forgotpassword/',views.forgotpassword,name='forgotpassword'),
    path('resetpassword_validate/<uidb64>/<token>/',views.resetpassword_validate,name='resetpassword_validate'),
    path('resetpassword/',views.resetpassword,name='resetpassword'),
    #path('otp_verification/', views.otp_verification, name='otp_verification'),
    path('',views.dashboard,name='dashboard'),
    path('my_orders/',views.my_orders,name='my_orders'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
    path('change_password/',views.change_password,name='change_password'),
    path('cancel_order/',views.cancel_order,name='cancel_order'),
    path('change_password/',views.change_password,name='change_password'),
    path('order_detail/<int:order_id>/',views.order_detail,name='order_detail'),
    #path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    
    
]

cart/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('', views.cart,name='cart'),
    path('add_cart/ <int:product_id>/',views.add_cart,name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart,name='remove_cart'),
    path('remove_cart_item/ <int:product_id>/<int:cart_item_id>/',views.remove_cart_item,name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
    #path('cart/checkout/<int:wallet_id>/', views.checkout, name='checkout')
    path('apply_coupon/',views.apply_coupon, name='apply_coupon'),
    path('remove-coupon/',views.remove_coupon, name='remove_coupon'),
    #path('save_address/', views.save_address, name='save_address'),
    

]

pjctmain/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.conf.urls.static import static
from django.conf import settings
#from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('store/',include('storeitem.urls')),
    path('accounts/',include('accounts.urls')),
    path('cart/',include('cart.urls')),
    path('', include('admin_soft.urls')),
    #path('dj-admin/',include('custom_admin.urls')),
    path('accounts/', include('allauth.urls')),
    #path('home/', TemplateView.as_view(template_name='accounts/login.html',name='login'))
    
    #orders
    path('orders/',include('orders.urls')),
    #path('customadmin/',include('customadmin.urls')),
    #path('coupons/',include('coupons.urls')),
    path('wishlist/',include('wishlist.urls')),
   
 ]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from .models import Account,UserProfile


class Registrationform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Enter Password',
        'class' : 'form-control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Confirm Password'  # this variable goes to register.html
    }))
    class Meta:
        model = Account
        fields = ['first_name','last_name','phone_number','email','password']

    def __init__(self,*args,**kwargs):
        super(Registrationform,self).__init__(*args,**kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter last Name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email Address'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'      # for applying form-control to all fields

    def clean(self):
        cleaned_data = super(Registrationform, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match"
            )
        

class Userform(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name','last_name','phone_number')

    def __init__(self,*args,**kwargs):
        super(Userform,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'      # for applying form-control to all fields


class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False,error_messages={'invalid':{"image files only"}},widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ('address_line_1','address_line_2','city','state','country','profile_picture')


    def __init__(self,*args,**kwargs):
        super(UserProfileForm,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control' 


class ReturnRequestForm(forms.Form):
    return_reason = forms.CharField(label='Reason for return', widget=forms.Textarea)
    # Add more fields as needed

accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import Registrationform,Userform,UserProfileForm
from .models import Account,UserProfile
from django.contrib import messages,auth
from django.views.decorators.cache import never_cache
from django.contrib.auth import authenticate
from django.contrib.auth.models import User,auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
# verification email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes,force_str
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
import random
from django.core.mail import send_mail
from django.contrib.auth.hashers import make_password
from datetime import datetime,timedelta
from orders.models import Order,OrderProduct,Payment
from cart.views import _cart_id
from cart.models import Cart,CartItem,PopularProduct
from django.db.models import F



# Create your views here.

@never_cache


def register(request):
    if request.method == 'POST':
        form = Registrationform(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']   # to fetch the data
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email.split("@")[0]
            user=Account.objects.create_user(first_name=first_name,last_name=last_name,email=email,username=username,password=password)  # inside create user pass all the fields
            user.phone_number =  phone_number
            user.save()

            # create user Profile
            profile = UserProfile()
            profile.user_id = user.id   # the id created when user signup is connecting with profile
            profile.profile_picture = 'default/default-user.png'
            profile.save()

            # USER ACTIVATION
            current_site = get_current_site(request)
            mail_subject = 'Please activate your account'
            message = render_to_string('accounts/account_verification_email.html',{
                'user' : user,
                'domain':current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),  # here encoding the primary key and nobody can see it and it decode when it activate
                'token' : default_token_generator.make_token(user)    # make token create token and pass to the user
            })
            to_email = email  # we got email from user and send to it
            send_email = EmailMessage(mail_subject, message ,to=[to_email])
            send_email.send()

            messages.success(request, 'Thank you for your registration.Please verify with the link in your gmail')
            return redirect('/accounts/login/?command=verification&email='+email)
    else:
        form = Registrationform()
    context = {
        'form' : form,  # form variable available in register.html
    }
    return render(request,'accounts/register.html',context)


def login(request):
    if request.method == 'POST':
        email=request.POST['email']
        password=request.POST['password']

        user=auth.authenticate(email=email,password=password)

        if user is not None:
            auth.login(request,user)
            #messages.success(request,'You are now logged in')
            return redirect('home')
        else:
            messages.error(request,'Invalid login credentials')
            return redirect('login')
    return render(request,'accounts/login.html')




@login_required(login_url='login') # we can logged out the system when you are log in.
def logout(request):
    auth.logout(request) 
    messages.success(request,'You are logged out.')
    return redirect('login')




def activate(request,uidb64,token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()   # decode the uidb and the value store in uid and it become primary key of user
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congratulations your account is activated.' )
        return redirect('login')
    else:
        messages.error(request, 'Invalid activation link.' )
        return redirect('register')



def forgotpassword(request):
    if request.method == 'POST':
        email =  request.POST['email']    #this email we get from forgotpassword form
        if Account.objects.filter(email=email).exists():
            user=Account.objects.get(email__exact=email)

            #Reset password email(same as email activation)
            current_site = get_current_site(request)
            mail_subject = 'Reset your password'
            message = render_to_string('accounts/reset_password_email.html',{
                'user' : user,
                'domain':current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),  # here encoding the primary key and nobody can see it and it decode when it activate
                'token' : default_token_generator.make_token(user)    # make token create token and pass to the user
            })
            to_email = email  # we got email from user and send to it
            send_email = EmailMessage(mail_subject, message ,to=[to_email])
            send_email.send()

            messages.success(request,'Resetting password sent to your email')
            return redirect('login')
        else:
            messages.error(request,'Account does not exist')
            return redirect('forgotpassword')

    return render(request, 'accounts/forgotpassword.html')


def resetpassword_validate(request,uidb64,token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()   # decode the uidb and the value store in uid and it become primary key of user
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid     #save uid here because we use this uid when reset password
        messages.success(request,'Reset your password')
        return redirect('resetpassword')
    else:
        messages.error(request,'This link has been expired!') 
        return redirect('login')
    

def resetpassword(request):
    if request.method == 'POST':
        password = request.POST['password']                  # for reset- uid saved only when you coming through validation link
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')   # for taking saved uid
            user = Account.objects.get(pk=uid)
            user.set_password(password)                   #we need to set password because simple saving makes error in django. if you set password ,django's inbuilt function take the password and save it in hash format
            user.save()
            messages.success(request,'Password Reset Successfully')
            return redirect('login')
        else:
            messages.error(request,'Password not matching')
            return redirect('resetpassword')
    
    else:
        return render(request, 'accounts/resetpassword.html')   # is the methosd is not POST this template will load


@login_required(login_url='login')
def dashboard(request):
    orders = Order.objects.order_by('-created_at').filter(user_id=request.user.id,is_ordered=True, status__in=['Completed','Cash_on_delivery'])
    orders_count = orders.count()

    
    context={
        'orders_count' : orders_count,
        
    }
    return render(request, 'accounts/dashboard.html',context)


@login_required(login_url = 'login')    
def my_orders(request):
    orders =  Order.objects.filter(user=request.user,is_ordered=True, status__in=['Completed','Cash_on_delivery']).order_by('-created_at')
   
    context = {
        'orders' : orders,
        
    }

    return render(request,'accounts/my_orders.html',context)


@login_required(login_url = 'login')
def edit_profile(request):
    
    userprofile = get_object_or_404(UserProfile, user=request.user)
    
    if request.method == 'POST':
        user_form = Userform(request.POST,instance=request.user)
        profile_form = UserProfileForm(request.POST,request.FILES,instance=userprofile)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,'Your profile has been updated')
            return redirect('edit_profile')
    else:
        user_form = Userform(instance=request.user)    # for seeing the existing data inside the form
        profile_form = UserProfileForm(instance=userprofile)
    context = {
        'user_form' : user_form,
        'profile_form' : profile_form,
        'userprofile' : userprofile,
    }

    return render(request,'accounts/edit_profile.html',context)


@login_required(login_url = 'login')
def change_password(request):
    if request.method == 'POST':
        
        current_password = request.POST['current_password']  # take this current password from change_password.html
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
        print('current_password ',current_password)
        user = Account.objects.get(username__exact=request.user.username)
        print('user',user)

templates/accounts/account_verification_email.html
{% autoescape off %}   <!--gives protection with cross site scripting when we pass activation email--> 

Hi {{user.first_name}},

Please click on below link to confirm your registration.
<a href="http://{{ domain }}{% url 'activate' uidb64=uid token=token %}">Activate your account</a>

If you think its not you,please ignore this email.

{% endautoescape %}

templates/accounts/dashboard.html
{% extends 'base.html' %}


{% block content %}

<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
        {% include 'includes/dashboard_sidebar.html'%}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Logged in as:</strong>
                <span>{{user.first_name}}</span>
            </header>
            <div class="card-body">
                <div class="row"> 
                   
                <div class="col-md-6">
                    <div class="card" style="text-align:center">
                        <div class="card-body">
                            <h5 class="card-title">Total Orders</h5>
                            <h4>{{orders_count}}</h4>
                            <a href="{% url 'my_orders' %}">View Order</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card" style="text-align:center">
                        <div class="card-body">
                            <img src="https://www.w3schools.com/howto/img_avatar2.png" alt="User Profile Picture" width="50" height="50" style="border-radius:50%">
                            <p class="mb-0">{{user.email}}</p>
                            <p>{{user.phone_number}}</p>
                        </div>
                    </div>
                </div>    
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
           
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}


{% block content %}

<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
        {% include 'includes/dashboard_sidebar.html'%}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Edit your profile</strong>
              
            </header>
            <div class="card-body">
                
                <div class="text-right">
                    <img src="{{userprofile.profile_picture.url}}" alt="Profile Picture" width="100" style="border-radius: 50px;">
                </div>
                <div class="row"> 
                <div class="col-md-12">
                    <form action="{% url 'edit_profile' %}" method="POST" enctype="multipart/form-data">     <!--form action for enable the editing & enctype="multipart/form-data is used to upload edited image file-->
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>First Name</label>
                                {{user_form.first_name}}
                            </div>
                            <div class="form-group col-md-6">
                                <label>Last Name</label>
                                {{user_form.last_name}}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>Phone Number</label>
                                {{user_form.phone_number}}
                            </div>
                            <div class="form-group col-md-6">
                                <label>Profile Picture</label>
                                {{profile_form.profile_picture}}
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Address Line 1</label>
                            {{profile_form.address_line_1}}
                        </div>
                        <div class="form-group">
                            <label>Address Line 2</label>
                            {{profile_form.address_line_2}}
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>City</label>
                                {{profile_form.city}}
                            </div>
                            <div class="form-group col-md-6">
                                <label>State</label>
                                {{profile_form.state}}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>Country</label>
                                {{profile_form.country}}
                            </div>
                        </div>
                        <input type="submit" value="save" class="btn btn-primary">
                    </form>
                </div>    
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
           
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/forgotpassword.html
{% extends 'base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
   

        <div class="card mx-auto" style="max-width: 500px; margin-top:100px;">
            
          <div class="card-body">
            {% include 'includes/alert.html' %}
          <h4 class="card-title mb-4">Forgot Password</h4>
          
            <form method="POST" action="{% url 'forgotpassword' %}">
            {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" name="email" >  <!--This email is from login email writen in accounts view-->
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url 'login' %}" class="float-right">Got password? Login</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Submit </button>
              </div> <!-- form-group// -->    
            </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% providers_media_js %}


{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
    {% if request.GET.command == 'verification' %}  <!--means you are not complete verification-->

    <div class="container mx-auto alert alert-info" style="max-width: 1024px; margin-top:100px;">
        Thank you for your registration.Please verify with the link in your gmail[{{request.GET.email}}]  <!--we get email from browser url--> 
        <br><br>
        Already verified? <a href="{% url 'login' %}">Login</a>
    </div>

    {% else %}

        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
            
          <div class="card-body">
            {% include 'includes/alert.html' %}
          <h4 class="card-title mb-4">Sign in</h4>
          
          
            <form method="POST" action="{% url 'login' %}">
            {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" name="email" >  <!--This email is from login email writen in accounts view-->
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" name="password">
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url 'forgotpassword' %}" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Login  </button>
              </div> <!-- form-group// -->    
            </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->

     
      <p class="text-center small text-muted mb-15">or sign up with</p>
      <div class="d-grid gap-3 mb-4">
          <a href="#" class="btn w-100 btn-light font-sm">
              <svg aria-hidden="true" class="icon-svg" width="20" height="20" viewBox="0 0 20 20">
                  <path d="M16.51 8H8.98v3h4.3c-.18 1-.74 1.48-1.6 2.04v2.01h2.6a7.8 7.8 0 002.38-5.88c0-.57-.05-.66-.15-1.18z" fill="#4285F4"></path>
                  <path d="M8.98 17c2.16 0 3.97-.72 5.3-1.94l-2.6-2a4.8 4.8 0 01-7.18-2.54H1.83v2.07A8 8 0 008.98 17z" fill="#34A853"></path>
                  <path d="M4.5 10.52a4.8 4.8 0 010-3.04V5.41H1.83a8 8 0 000 7.18l2.67-2.07z" fill="#FBBC05"></path>
                  <path d="M8.98 4.18c1.17 0 2.23.4 3.06 1.2l2.3-2.3A8 8 0 001.83 5.4L4.5 7.49a4.77 4.77 0 014.48-3.3z" fill="#EA4335"></path>
              </svg> Sign in using Google
          </a>
          <a href="#" class="btn w-100 btn-light font-sm">
            <svg aria-hidden="true" class="icon-svg" width="20" height="20" viewBox="0 0 20 20">
                <path d="M3 1a2 2 0 00-2 2v12c0 1.1.9 2 2 2h12a2 2 0 002-2V3a2 2 0 00-2-2H3zm6.55 16v-6.2H7.46V8.4h2.09V6.61c0-2.07 1.26-3.2 3.1-3.2.88 0 1.64.07 1.87.1v2.16h-1.29c-1 0-1.19.48-1.19 1.18V8.4h2.39l-.31 2.42h-2.08V17h-2.5z" fill="#4167B2"></path>
            </svg> Sign in using Facebook
          </a>
      </div>
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    {% endif %}
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/my_orders.html
{% extends 'base.html' %}


{% block content %}

<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
        {% include 'includes/dashboard_sidebar.html'%}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Your order history</strong>
              
            </header>
            <div class="card-body">
                <div class="row"> 
                <div class="col-md-12">
                    <table class="table table-hover">
                        <thead>
                          <tr>
                            <th scope="col">Order #</th>
                            <th scope="col">Billing Name</th>
                            <th scope="col">Phone</th>
                            <th scope="col">Price</th>
                            <th scope="col">Date</th>
                            <th scope="col">Status</th>
                            <th scope="col">Cancel Order</th>
                            <!--<th scope="col">Return Order</th>-->
                          </tr>
                        </thead>
                        <tbody>
                          {% for order in orders %}
                          <tr>
                            <th scope="row"><a href="{% url 'order_detail' order.order_number %}">{{order.order_number}}</th>
                            <td>{{order.full_name}}</td>
                            <td>{{order.phone}}</td>
                            <td>{{order.order_total}}</td>
                            <td>{{order.created_at}}</td>
                            <td>{{order.status}}</td>
                           
                            <td>
                              
                              <a href="{% url 'cancel_order' order_id=order.id %}" class="btn btn-danger">Cancel</a>
                              
                            </td>
                            <!--<td>
                              
                              <a href="{% url 'return_request' order_id=order.id %}" class="btn btn-danger">Return</a>
                              
                            </td>-->
                           
                          </tr>
                          {% endfor %}
                          
                          
                        </tbody>
                      </table>   
                </div>    
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
           
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/otp_registration_email.html
{% extends 'base.html' %}

{% block content %}
    <p>Your OTP for registration is: {{ otp }}</p>     <!--template for otp verification-->
{% endblock %}

templates/accounts/return_request.html
{% extends 'base.html' %}


{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Return Request</title>
</head>
<!--<body>
    <h1>Return Request Form</h1>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="id_return_reason">Reason for return:</label><br>
            {{ form.return_reason }}
        </div>
        //Add more form fields here if needed 
        <button type="submit">Submit Return Request</button>
    </form>
</body> -->
<body>

  <div class="container mt-5">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Return Request Form</h5>
            <form method="post" >
              {% csrf_token %}
              <div class="form-group">
                <label for="returnReason">Return Reason:</label>
                <textarea class="form-control" id="returnReason" name="return_reason" rows="3"{{ form.return_reason }}></textarea>
              </div>
               <!-- Display user's wallet balance if available -->
               {% if wallet %}
               <div class="form-group">
                 <label for="walletBalance">Your Wallet Balance:</label>
                 <input type="text" class="form-control" id="walletBalance" value="{{ wallet.balance }}" readonly>
               </div>
               {% endif %}
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  </body>
</html>

{% endblock %}